Repository DP2-C1-046/Acme-ANS-D04, pull requests merged in 2025-03, with the labels that each got.

#113 Student#2 - T003 - Customers
  src/main/java/acme/realms/Customer.java
Labels: coding, needs testing, Mandatory

#117 feat(aircraft): added aircraft entity with restrictions and validations
  src/main/java/acme/entities/Aircraft.java
  src/main/java/acme/entities/DUMMY.txt
Labels: coding, needs testing, Mandatory

#119 Student#2 T004 Booking
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/bookings/TravelClass.java
  src/main/java/acme/entities/services/Service.java
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: coding, needs testing, Mandatory

#132 [Group] T006/R - Gestión de Aeronave
  src/main/java/acme/entities/aircrafts/Aircraft.java
  src/main/java/acme/entities/aircrafts/AircraftStatus.java
Labels: coding, Mandatory

#136 [Student1] T004 - Flights
  src/main/java/acme/entities/flights/Flight.java
Labels: coding, rafseggom, needs testing, Mandatory

#135 [Student1] T003 - Airline managers
  src/main/java/acme/realms/AirlineManager.java
Labels: coding, rafseggom, needs testing, Mandatory

#130 [Student5] T006 - Test Technicians
  reports/D02/Student #5/05 - Requirements - Student #5.docx
  src/main/java/acme/entities/technicians/Technicians.java
  src/main/resources/WEB-INF/data/sample/technicians.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: needs testing, emiespeli, Mandatory, testing

#127 [Student5] T003 - Technicians
  reports/D02/Student #5/05 - Requirements - Student #5.docx
  src/main/java/acme/entities/technicians/Technicians.java
Labels: coding, needs testing, emiespeli, Mandatory

#128 [Student5] T004 - Maintenance Records
  src/main/java/acme/entities/maintenaceRecords/MaintenanceRecords.java
  src/main/java/acme/entities/maintenaceRecords/MaintenanceRecordsStatus.java
Labels: coding, needs testing, emiespeli, Mandatory

#141 [Group] T004 - Gestión de Aeropuerto
  src/main/java/acme/entities/airport/Airport.java
  src/main/java/acme/entities/airport/OperationalScope.java
Labels: coding, needs testing, Mandatory

#142 Student#3 individual task4 done!
  src/main/java/acme/entities/assignments/AssignmentStatus.java
  src/main/java/acme/entities/assignments/FlightAssignment.java
  src/main/java/acme/entities/assignments/FlightCrewDuty.java
  src/main/java/acme/realms/FlightCrewMember.java
  src/main/resources/WEB-INF/data/sample/FlightAssignment.csv
Labels: coding, davblamor, needs testing, Mandatory

#155 fix(Claims): Arreglada relación
  src/main/java/acme/entities/claims/Claim.java
Labels: nerjimado, coding, needs testing, Mandatory

#154 feat(TrackinLog): Validador Custom, arreglos y repo
  src/main/java/acme/constraints/TrackingLogValidator.java
  src/main/java/acme/constraints/ValidTrackingLog.java
  src/main/java/acme/entities/claims/TrackingLog.java
  src/main/java/acme/entities/claims/TrackingLogRepository.java
  src/main/java/acme/entities/claims/TrackingLogStatus.java
Labels: nerjimado, coding, needs testing, Mandatory

#170 feat: added CustomersDashboard form
  src/main/java/acme/forms/CustomersDashboard.java
Labels: coding, rafcarmed, Supplementary I

#175 Student#2-T016-UML Diagrams
  reports/D02/Student #2/Domain-Model/Student#2-Entities-UML-Diagram.png
  reports/D02/Student #2/Domain-Model/Student#2-Realms-UML-Diagram.png
  reports/D02/Student #2/Domain-Model/Student_2_Entities.uxf
  reports/D02/Student #2/Domain-Model/Student_2_Realms.uxf
Labels: documentation, rafcarmed, Supplementary I

#258 T013 group requisite!
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftListService.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftUpdateService.java
  src/main/resources/WEB-INF/views/administrator/DUMMY.txt
  src/main/resources/WEB-INF/views/administrator/aircraft/form.jsp
  src/main/resources/WEB-INF/views/administrator/aircraft/list.jsp
  src/main/resources/WEB-INF/views/administrator/aircraft/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/aircraft/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: coding, Mandatory
