Repository DP2-C1-046/Acme-ANS-D04, pull requests merged in 2025-02, with the labels that each got.

#17 Student3 Task1 Done!
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: coding, needs testing, Mandatory

#35 Done Student1 Task 001
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: coding, needs testing, Mandatory

#38 Student2 task1 modify anonymous menu
  reports/Student #2/02 - Requirements - Student #2.docx
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: coding, needs testing, Mandatory

#44 doc: added "Analysis" and "Plannig and Progress" individual reports, and
  reports/Student #2/02 - Requirements - Student #2.docx
  reports/Student #2/Student2-D01-Analysis Report.docx
  reports/Student #2/Student2-D01-Planning and Progress Report.docx
Labels: documentation, emiespeli, Supplementary II

#104 Student#2 - [Group Req] T007 - Creation of the `Service` entity
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/entities/Service.java
Labels: coding, rafcarmed, Mandatory

#112 feat: updated the name of two attributes to CamelCase
  src/main/java/acme/entities/Service.java
Labels: coding, rafcarmed, Mandatory
